language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit -d error_reporting=24575 --coverage-clover=coverage.xml
